### ISSUE TITLE
Can't add configuration to Webstorm

### ISSUE THREAD

**Issue by emahuni** [ericjgagnon/vitest-run-debug-config#1]
The plugin isn't working with my IDE - Webstorm 2022.2
```
java.lang.IllegalStateException: @NotNull method com/github/ericjgagnon/vitest/run/VitestRunConfiguration.getSettings must not return null
	at com.github.ericjgagnon.vitest.run.VitestRunConfiguration.$$$reportNull$$$0(VitestRunConfiguration.java)
	at com.github.ericjgagnon.vitest.run.VitestRunConfiguration.getSettings(VitestRunConfiguration.java:44)
	at com.github.ericjgagnon.vitest.run.VitestRunConfigurationProducer.setupConfigurationFromCompatibleContext(VitestRunConfigurationProducer.java:45)
	at com.github.ericjgagnon.vitest.run.VitestRunConfigurationProducer.setupConfigurationFromCompatibleContext(VitestRunConfigurationProducer.java:31)
	at com.intellij.execution.actions.CompatibleRunConfigurationProducer.setupConfigurationFromContext(CompatibleRunConfigurationProducer.java:30)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:100)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:119)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:100)
	at com.intellij.execution.actions.ConfigurationContext.createConfigurationsFromContext(ConfigurationContext.java:423)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.getRunConfigsForCurrentFile(ExecutorRegistryImpl.java:462)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.getRunCurrentFileActionStatus(ExecutorRegistryImpl.java:408)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.getRunCurrentFileActionStatus(ExecutorRegistryImpl.java:404)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.update(ExecutorRegistryImpl.java:345)
	at com.intellij.execution.ExecutorRegistryImpl$RunCurrentFileExecutorAction.update(ExecutorRegistryImpl.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:150)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:660)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:116)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:649)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:526)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:477)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1398)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:477)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$12(ActionUpdater.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$13(ActionUpdater.java:359)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$17(ActionUpdater.java:391)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:387)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:359)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:358)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

I can't use it to "add new configuration..." (after clicking the "+" icon) though it appears in the list:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/7290508/185060750-1813cca5-370a-4fa0-ac4e-143bb465cc0a.png">

It sort of adds a folder to the configurations list like below, but doesn't close the above choices list when I click it. NB: I can't remove it from the configurations list with the "-" icon, it's as if it's not there, like it's just a folder, but has no configuration file in it (it's as if it didn't finish something after I clicked it in the choice list). 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/7290508/185061802-b378777d-6f04-4f47-a72e-10ae55a49620.png">

Unlike if I choose anything else from the list like Mocha, it just jumps to the config from the choice list, NB it has like a file in a folder unlike the above:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/7290508/185062153-d8be1155-2664-4c50-8358-43343505bdee.png"> => 
<img width="853" alt="image" src="https://user-images.githubusercontent.com/7290508/185062255-8fda474f-b6ed-42e2-aa7d-a1af98bcfb02.png">

If I click Edit configuration templates below, I can see the configuration and can change it, but nothing happens, and that config will revert to the same thing if I come back to do it again:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/7290508/185060470-10b4a5ff-9dc3-4771-8587-c60299407ea2.png">

NOTES: 
My project doesn't use vite at all, I am just using vitest instead of jest. It's a Nodejs application.

**Comment by emahuni** [comment]
So I managed to hack into it this way: 
I opened my project workspace.xml file
<img width="214" alt="image" src="https://user-images.githubusercontent.com/7290508/185075287-6b043778-988e-4db5-9260-15a0a47f6f43.png">
and added the following nodes under <component name="RunManager"> : 
```xml
    <configuration name="app.test.js" type="JavaScriptTestRunnerVitest" temporary="true" nameIsGenerated="true">
      <node-interpreter value="project" />
      <vitest-package value="$PROJECT_DIR$/node_modules/vitest" />
      <vitest-config value="$PROJECT_DIR$/vitest.config.ts" />
      <working-dir value="$PROJECT_DIR$" />
      <test-file-path value="$PROJECT_DIR$/tests/app.test.js" />
      <test-scope value="TEST_FILE" />
      <method v="2" />
    </configuration>
```
Then I was able to edit it's configuration in Webstorm
<img width="279" alt="image" src="https://user-images.githubusercontent.com/7290508/185075903-54778993-5e2e-4db2-b943-0cc6bfab5c0b.png">
<img width="543" alt="image" src="https://user-images.githubusercontent.com/7290508/185075985-49583ee3-8f92-43dd-9231-0e5383a81cb0.png">

But then ran into issue: #2
